export const TODOS_ADD = 'TODOS_ADD';
export const TODOS_DELETE = 'TODOS_DELETE';
export const TODOS_EDIT = 'TODOS_EDIT';
export const TODOS_COMPLETE = 'TODOS_COMPLETE';
export const TODOS_COMPLETE_ALL = 'TODOS_COMPLETE_ALL';
export const TODOS_CLEAR_COMPLETE = 'TODOS_CLEAR_COMPLETE';